### ISSUE TITLE
Cannot load animation

### ISSUE THREAD

**Issue by helloelwin** [Carbonadooo/ENGG1340-Group-Project#6]
Hi, I find that the animation is not showing up, how can I fix it? Thx!

**Comment by Carbonadooo** [comment]
I am so sorry to tell you that we don't intend to make animation in this game. But if you want, you could join us for animations developing.

**Comment by helloelwin** [comment]
> I am so sorry to tell you that we don't intend to make animation in this game. But if you want, you could join us for animations developing.

Great! May I know the average weekly salary?

**Comment by Carbonadooo** [comment]
Yes, it’s about 0 HKD weekly in the early stage. And after we start to make profits the salary may rise.😊

**Comment by helloelwin** [comment]
> Yes, it’s about 0 HKD weekly in the early stage. And after we start to make profits the salary may rise.😊

Got it, thanks a lot, boss! 🙏
